version: '2'

linters-settings:
  errcheck:
    exclude-functions:
      - fmt:.*
    check-blank: false

  revive:
    rules:
      - name: package-comments
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - unparam
    - exhaustive
    - misspell
    - unconvert
  
  # Exclude error checking issues in example files only
  # Examples are demonstration code where verbosity from error handling would obscure the API being demonstrated
  # Production code in cmd/ and internal/ must handle all errors properly
  exclusions:
    rules:
      - path: ^examples/
        linters:
          - errcheck
          - gocritic
          - revive
          - staticcheck

run:
  timeout: 5m
  tests: false

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
