name: Update README on Release

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Get release info
        id: release
        run: |
          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%B %Y')" >> $GITHUB_OUTPUT
      
      - name: Update README version
        run: |
          # Update version line
          sed -i "s/\*\*Current Version\*\*: v[0-9]*\.[0-9]*\.[0-9]*/\*\*Current Version\*\*: ${{ steps.release.outputs.version }}/" README.md
          
          # Update release date
          sed -i "s/\*\*Released\*\*: [A-Za-z]* [0-9]*/\*\*Released\*\*: ${{ steps.release.outputs.date }}/" README.md
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update README version to ${{ steps.release.outputs.version }}"
          title: "docs: update README version to ${{ steps.release.outputs.version }}"
          body: |
            Automatically update README.md version info after release.
            
            - Version: ${{ steps.release.outputs.version }}
            - Date: ${{ steps.release.outputs.date }}
          branch: auto/update-readme-${{ steps.release.outputs.version }}
          base: master
